### ISSUE TITLE
Suggestion: more compact waypoint listing

### ISSUE THREAD

**Issue by jason-green-io** [PouekDEV/CList#10]
I'd be nice to have waypoints listed on one line instead of 2 on the waypoint list UI. Visibility, coords button, dimension and edit button should all be inline.

**Comment by PouekDEV** [comment]
I know this would be better but I'm still trying to figure out how to go about doing it. I'm sure I'm gonna figure it out soon.

**Comment by PouekDEV** [comment]
I found a really nice compact design. I implemented it and it will be available in the next update.
Here's how it looks:
![image](https://github.com/PouekDEV/CList/assets/64737924/b1547380-9a73-4293-9e6c-88808a222679)
