### ISSUE TITLE
[Feature Request] Set name for waypoint when creating it

### ISSUE THREAD

**Issue by jwaxy** [PouekDEV/CList#13]
So if you create a waypoint using the keybind it will be New Waypoint and I think that it would be better if we press the keybind a pop up dialog will open and ask for the name and there will be a cancel and create buttons so with this feature we can make it so we dont create waypoints by mistake too and we can cancel them if we don't want to create it.

**Comment by PouekDEV** [comment]
Thanks for the suggestion. I already implemented it and it will be available in the next update!

**Comment by jwaxy** [comment]
Thank you. You're an amazing developer!
