### ISSUE TITLE
Bug - copy-pasting into fields when editing waypoint doesn't save changes

### ISSUE THREAD

**Issue by Fluboxer** [PouekDEV/CList#14]
Couldn't come up with better title 

Steps to replicate are simple: 

1. Create waypoint
2. Open editor and try to paste in other name or cords or color - anything, really
3. If you do so, changes won't be registered

There is a way around - you just click on box and manually add space or just manually type anything into it and it will cause it to update and actually react to this

possible simple fix - when you click "Done" ("Готово") button it will check contents of fields and force them into waypoint

**Comment by PouekDEV** [comment]
Good catch. There were apparently more issues with those TextWidgets but now in the next update hopefully they are fixed.
