### ISSUE TITLE
[Feature Request] Sharing waypoint/cords in chat

### ISSUE THREAD

**Issue by Fluboxer** [PouekDEV/CList#16]
Sometimes you just want to share place you are at or some of your waypoints 
I personally see it as both button and keybing

Button would be in GUI, allowing you to share selected waypoint - by opening your chat and putting message with cords and name of selected waypoint 
Keybind could be same button that makes waypoint - if you click it when with open chat, it will paste your current cords in. Fill name of it, fill them in command or just dump those cords in chat - its all up to user 

Automatically sending message could be an option in config that is off by default - there are use cases for it, but I believe user generally want more control over what they send in chat, allowing for both adding information and extra layer of fool proofing ("what? I missclicked and almost shared my super secret place instead of my dirt house? Glad that it won't send it without my second input!")

**Comment by PouekDEV** [comment]
Well, that sounds awfully similar to the button that already exists. It allows you to copy the selected waypoint coordinates and then paste them into the chat.
![image](https://github.com/PouekDEV/CList/assets/64737924/825fa3ef-5da9-461f-be6a-cb758c3f36b5)

**Comment by Fluboxer** [comment]
Yep, that's it! 
I thought it is just a way to show what's inside of a waypoint without opening it
