### ISSUE TITLE
[Feature Request] Parsing cords from chat 

### ISSUE THREAD

**Issue by Fluboxer** [PouekDEV/CList#17]
That one is a bit more niche and complex than previous one 

Currently fastest way of mindlessly getting cords someone else shared is this:

1. Copy their chat message using external mod (ChatUtils for example)
2. Open new waypoint 
3. Paste message in name to have cords 
4. Copy-paste/Manually type cords in each box
5. Cut message to have only name remaining/Clear name box and fill it manually 
6. Profit? 

If you need to do this once - not much of an issue, but in some dynamic scenario where you go trough quite a few waypoints... it kinda sucks 

I once had mod that were reading chat messages and if it contained cords - it were suggesting adding it as waypoint - with either one of preset names or with custom name so maybe we can have it too?

**Comment by PouekDEV** [comment]
Implemented and will be available in the next update!
