### ISSUE TITLE
[Feature Request] config for enable/disable mod when joining world

### ISSUE THREAD

**Issue by FatPorpoise** [PouekDEV/CList#20]
When I'm staying in one place a lot (at base or building something) I don't use coords. I have to turn the mod off everytime I load my world. It'd be more comfortable to set it to not show after loading or remember if it was on or off when saving world.
Thanks in advance!

**Comment by PouekDEV** [comment]
Hey!
Thanks for the suggestion. I already implemented it and it will be available in the next update.
