### ISSUE TITLE
The waypoints should be different in every world/server, but it just merges all existing waypoints into one world/server.

### ISSUE THREAD

**Issue by FastPhase** [PouekDEV/CList#23]

**Comment by PouekDEV** [comment]
I will need more information regarding your issue. For example, on what server you are playing, what are you doing and what is the expected behavior.

**Comment by FastPhase** [comment]
> I will need more information regarding your issue. For example, on what server you are playing, what are you doing and what is the expected behavior.

okay so the problem is that i have 2 worlds which i play on, and i have waypoints according to individual worlds, but the problem is that the waypoints for individual worlds are not individual for each world, it is the same in every world i play on, for example:
i have existing waypoints which i created in a world i play on,
as i create a new world and play the waypoints from my previous world is present in the newly created world,
it sort of just merges all the existing waypoints of every created waypoints regardless of the world.

same story with server,

**Comment by PouekDEV** [comment]
OK. 
If you could provide your minecraft logs (using https://mclo.gs/) while playing on these two worlds with a screenshot of your 
`.minecraft/config/coordinatelist` directory, that'd be great.
