### ISSUE TITLE
Option to display 'Delete' on main panel

### ISSUE THREAD

**Issue by jr0n** [PouekDEV/CList#33]
I'm a heavy user of CList and believe a small UI change would make a large QOL improvement: moving the delete option from the Edit panel to the main panel would save a lot of clicks and mouse movement when death markers, temporary locations, etc. accumulate. 

Users would be unlikely to accidently click the Delete button by mistake because, as currently designed, a waypoint needs to be selected before the buttons are available. This would also include the delete button.

A config option to move the button would be another alternative.

Thanks for making CList!

**Comment by PouekDEV** [comment]
This sounds great, and thanks for using the mod. I'll look into it!

**Comment by PouekDEV** [comment]
I implemented your suggestion, and it will be available in the next update!
Here's a little sneak peek.

![obraz](https://github.com/PouekDEV/CList/assets/64737924/8ea463f1-2573-4de6-afb8-646afabeb008)
