### ISSUE TITLE
what is the Hotkey for placing a waypoint in the current position.

### ISSUE THREAD

**Issue by Red05Wins** [PouekDEV/CList#44]
Please, what is the Hotkey for placing a waypoint in the current position.
i dont know how to use your mode, 
Thanks

**Comment by PouekDEV** [comment]
The hotkey for placing a waypoint in the current position is **"B"**.
You can see and change all the hotkeys of all the mods you have under Settings > Controls > Key Binds and scrolling down to the category of the mod you're trying to change the bindings of.
![image](https://github.com/user-attachments/assets/029b5f58-7d76-43b2-ace4-c5d37f63294c)
