### ISSUE TITLE
feature request: tags

### ISSUE THREAD

**Issue by jason-green-io** [PouekDEV/CList#8]
allow tagging certain coords, then being able to toggle whole tags on and off from within the coordinate list. not looking for another key bind, the global toggle is fine, just a way to filter what is displayed

**Comment by jason-green-io** [comment]
dude, you're on fire!
nice work, will test in a few hours

**Comment by PouekDEV** [comment]
Thanks! Although I have to mention that instead of tags I made a more simple minimalistic adaptation of your idea that I think suits the mod more. I added a little icon/button that toggles the visibility of the selected waypoint in the list.

**Comment by jason-green-io** [comment]
It's a start :) I was thinking on a large multiplayer servers, if you have
many waypoints in the form of farms, bases, nether portals .. you could
clear the clutter by only rendering categories you need at the time. But I
appreciate this.
