### ISSUE TITLE
Update to 1.20.1

### ISSUE THREAD

**Issue by Depastet47** [PouekDEV/CList#9]
A very cool mod, so could you update it to the newest version?

**Comment by PouekDEV** [comment]
I'm currently trying my best to rewrite the waypoint name rendering system. The functions I used got replaced in 1.20 and I'm trying my best to rewrite the system using the player name tags rendering system. It's excruciating to implement and I don't know how long it will take me to finish, but I'm hoping to release an update for the newest version soon.

**Comment by PouekDEV** [comment]
I finally got it working. I'll release the new version soon
